# Generated by Django 5.2.3 on 2025-07-29 13:20

from django.db import migrations

def create_user_profile (apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('accounts', 'Profile')
    for user in User.objects.all():
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_profile, migrations.RunPython.noop),
    ]
