# Generated by Django 5.2.3 on 2025-07-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_article_author_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_article_status', 'Can change article status')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
